name: Check Formatting

on: [push, pull_request]

jobs:
  format:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Rustfmt
      run: rustup component add rustfmt
    - name: Check formatting
      run: cargo fmt -- --check