name: Lint with Clippy

on: [push, pull_request]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Lint code with Clippy
      run: cargo clippy -p sec_msg --all-targets --all-features -- --no-deps -D warnings
