name: Semantic Release Versioning

on: [push]

jobs:
  versioning:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Wait for other checks to pass
      run: |
        curl \
          --request GET \
          --url https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/status \
          --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          --header "Accept: application/vnd.github.v3+json" \
          | jq '.statuses[] | select(.context == "format" or .context == "lint" or .context == "test" or .context == "security") | .state' \
          | grep -v '"success"' && exit 1 || exit 0
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
    
    - name: Install dependencies
      run: npm install @semantic-release/changelog @semantic-release/commit-analyzer @semantic-release/github @semantic-release/git @semantic-release/release-notes-generator semantic-release
    
    - name: Run semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npx semantic-release